[package]
name = "eloquent_core"
version = "2.0.0"
edition = "2021"
license = "MIT"
description = "Core query builder component for Eloquent."
repository = "https://github.com/tjardoo/eloquent-rs"
documentation = "https://docs.rs/eloquent"

[dependencies]
sqlformat = "0.2.0"

[lib]
doctest = true
