[package]
name = "eloquent-demo"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = ["eloquent", "eloquent_core"]

[dependencies]
eloquent = { path = "eloquent", version = "2.0" }
log = "0.4"
ftail = "0.3"
